blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://github.com/jmkerloch/qgis-templater-test
    about: Please read carefully the documentation before to submit an issue.
